# Generated by Django 4.0.3 on 2022-04-13 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_digital_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='In Stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Unit Price'),
        ),
    ]
