# Generated by Django 4.0.3 on 2022-04-14 11:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Order ID'),
        ),
    ]
