# Generated by Django 4.0.3 on 2022-04-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_billingaddress_delete_customeraddresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'ordering': ['eircode']},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['eircode']},
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.billingaddress', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingaddress', verbose_name='Shipping Address'),
        ),
    ]
