# Generated by Django 4.0.3 on 2022-04-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_billingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'ordering': ['eircode'], 'verbose_name': 'Billing Address', 'verbose_name_plural': 'Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name'], 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['eircode'], 'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='product',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_shipment', 'Awaiting Shipment'), ('shipped', 'Shipped')], max_length=50, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
