# Generated by Django 4.0.3 on 2022-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_billingaddress_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='size',
            field=models.TextField(blank=True, null=True, verbose_name='Size'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'size')},
        ),
    ]
