# Generated by Django 4.0.3 on 2022-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_stock_size_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_size',
            field=models.CharField(default='Normal', max_length=5, verbose_name='Product Size'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'product_size')},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='size',
        ),
    ]
