# Generated by Django 4.0.3 on 2022-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10, verbose_name='Gender'),
        ),
    ]
