# Generated by Django 4.0.3 on 2022-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_size_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=10, verbose_name='Size'),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('size', 'gender')},
        ),
    ]
