# Generated by Django 4.0.3 on 2022-04-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_size_size_alter_size_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['organisation', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['gender'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.billingaddress', verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingaddress', verbose_name='Shipping Address'),
        ),
    ]
